[package]
name = "devenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
color-eyre = "0.6.1"
paris = { version = "1.5.11", features = ["macros", "no_logger"] }
